# Generated by Django 3.1.7 on 2021-05-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('current_price', models.IntegerField()),
                ('starting_bid', models.IntegerField()),
                ('img_url', models.CharField(max_length=420)),
            ],
        ),
    ]
