# Generated by Django 3.1.7 on 2021-05-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210513_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='id',
        ),
        migrations.AlterField(
            model_name='auction',
            name='title',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
