# Generated by Django 3.1.7 on 2021-05-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210525_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='listingid',
        ),
        migrations.AddField(
            model_name='comment',
            name='listing',
            field=models.CharField(default='UnknownListing', max_length=64),
        ),
    ]
