# Generated by Django 3.1.7 on 2021-05-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210525_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='creator',
            field=models.CharField(default='UnknownCreator', max_length=64),
        ),
    ]
