# Generated by Django 3.1.7 on 2021-05-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210525_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='UnknownUser', max_length=24)),
                ('listing', models.CharField(default='UnknownListing', max_length=64)),
            ],
        ),
    ]
