# Generated by Django 3.1.7 on 2021-05-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210527_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='id',
            field=models.CharField(default='UnknownId', max_length=24, primary_key=True, serialize=False),
        ),
    ]
