# Generated by Django 3.1.7 on 2021-06-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20210527_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.CharField(default='UnknownListing', max_length=64),
        ),
    ]
