# Generated by Django 3.1.7 on 2021-06-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_bid_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='unknown', max_length=20)),
                ('listing', models.CharField(default='UnknownListing', max_length=64)),
            ],
        ),
    ]
