# Generated by Django 3.1.7 on 2021-06-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20210614_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='closed',
            field=models.CharField(default='False', max_length=20),
        ),
    ]
