# Generated by Django 3.1.7 on 2021-06-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20210614_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('cars', 'CARS'), ('food', 'FOOD'), ('clothes', 'CLOTHES'), ('musical instruments', 'MUSICAL INSTRUMENTS')], default='cars', max_length=20),
        ),
    ]
